### ISSUE TITLE
lrexlib-posix doc/ is not readable by everyone

### ISSUE THREAD

**Issue by Nomarian** [rrthomas/lrexlib#40] opened 2021-08-25 02:34 UTC
The files are everything residing in doc/ which happens to not have reading permission for everyone, just user: rw and group: r, but not other

**Comment by tst2005** [comment] 2021-08-25 15:26
Hello,
Git does not remind permissions.
It is an issue on our side.
You just have to change your umask.

For example:
```bash
$ umask 077
$ cd /tmp
$ git clone https://github.com/rrthomas/lrexlib
$ ls -logd lrexlib/doc lrexlib/doc/*
drwx------ 2  4096 Aug 25 17:24 lrexlib/doc
-rw------- 1  5524 Aug 25 17:24 lrexlib/doc/html4css1.css
-rw------- 1  1249 Aug 25 17:24 lrexlib/doc/license.html
-rw------- 1   452 Aug 25 17:24 lrexlib/doc/lrexlib.css
-rw------- 1 45068 Aug 25 17:24 lrexlib/doc/manual.txt
-rw------- 1    85 Aug 25 17:24 lrexlib/doc/SciTE.properties
```

You probably want this:
```bash
$ umask 022
$ cd /tmp
$ git clone https://github.com/rrthomas/lrexlib
$ ls -ld lrexlib/doc lrexlib/doc/*
drwxr-xr-x 2  4096 Aug 25 17:25 lrexlib/doc
-rw-r--r-- 1  5524 Aug 25 17:25 lrexlib/doc/html4css1.css
-rw-r--r-- 1  1249 Aug 25 17:25 lrexlib/doc/license.html
-rw-r--r-- 1   452 Aug 25 17:25 lrexlib/doc/lrexlib.css
-rw-r--r-- 1 45068 Aug 25 17:25 lrexlib/doc/manual.txt
-rw-r--r-- 1    85 Aug 25 17:25 lrexlib/doc/SciTE.properties
```

**Comment by rrthomas** [comment] 2023-06-02 19:17
Closing as not a bug.

**Closed by rrthomas** 2023-06-02 19:17 UTC
